---
title: 'Project 2: Analyzing  Weather Data'
author: "Chris van Hasselt"
date: "Thursday, August 21, 2014"
output: html_document
---

## Synopsis

Severe weather events disrupt the lives of individuals, families, and communities wherever they occur.  Injuries, fatalities, and property damage attributed to severe weather events strain the financial resources of responsible government agencies, and non-governmental actors involved in disaster response.  Disaster responders are motivated to find appropriate preventative measures that will minimize the impact of severe weather events.

This project involves exploring the U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database. This database tracks characteristics of major storms and weather events in the United States, including when and where they occur, as well as estimates of any fatalities, injuries, and property damage.

The data-set used includes data from 1950 through November, 2011.  For purposes of this analysis, data prior to 1990 is excluded.  In 1990, the Intergovernmental Panel on Climate Change (IPCC) issued its first report concluding 

## Data Processing

The data is available from the following URL:
https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2


```{r} 
# Download the file. 
download.file("http://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2", "data/StormData.bz2")

# Loading data

weatherData <- read.csv(bzfile("data/StormData.bz2"),header=TRUE)

```


## Results